# -*- coding: utf-8 -*-
"""assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eMRjHYbA1F_imrviqjJIdiSXwnp5pGd9
"""

# Q2 Take a string data and capitalize the last letter of each word
# "regex Software"   => "regeX SoftwarE"
# "naina"  => "nainA"

#(1).
x="regex softwere "
for i in x.split():
    print(i[:-1]+i[-1].upper(),end=" ")

#(2).
x="naina"
print(x[:-1]+x[-1].upper())

#(3).
x="naina"
print(x[0:-1]+x[-1].upper())

# user string
# valid Paranthesis
# {}[] => valid
# {}( ] ) => invalid
# { [ ()] } => valid

a=input("enter string")
valid_parenthesis=["{}[]","[]","()","{}"]
if a in valid_parenthesis:
    print("valid")
else:
    print("invalid")

