# -*- coding: utf-8 -*-
"""day1basicpython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pi0EKalSJZN1XxCRIt8fa01zz3iUZUVV
"""

print("hello world")

print('hello world')

print("hello world")
print("hey shiv")

#bina \n ke bhi agli line me aana ?
print("hello \n world")
print("hey shiv")

# python me print function ke under ek option hota h jiska name hota h end option jiski value \n hoti h to python me kisi bhi value ko agli line me print krvane ke liye \n likhnw ki jarurat nhi hoti h .
print("hello world", end = "\n")
print("hey shiv")
# y \n likho ya na likho koi farak nhi pdta h

# \n ki value cange ho skti h .
# ex.
print("hello  world", end="$")
print("hey shiv")

# ham end ki value kuchh bhi likh skte h
# ex.
print("hello  world", end="^")
print("hey shiv")

print("hello  world", end=" ")
print("hey shiv")

print("hello  world", end=" ")
print("hey shiv")
print("task")
# task agli line me print hoga kyunki 2nd line me end ki value \n hi h jo by default h .
# agar 2nd line me bhi end ki value " " ko add kr di jaye to vo bhi " hello world hey shiv task " is tarike se print hoga

x=10
print(x)

x="10"
print(x)

# DATA TYPE CHECK
# data type means kis type value usme store h ya usne hold ki h
x="10"
print(x)
print(type(x))

x=10
print(x)
print(type(x))

address="jaipur,indea"
print(address)
print(   type (address) )
# ham code me kitna bhi white space de skte h .
# but jitna clear likhoge utna achha h .

# MULTI LINE STR.
# str. ko muliple line me likhne ke liye """___""" ke ander likha jata h
address="""jaipur,indea
302018 """
print(address)
print(   type (address) )

address="""jaipur,indea
302018 """
print(address)

address='''jaipur
indea
302018 '''
print(address)

# COMMENTS
# to understand the code and logic
# K.T. = knowledge transfer
# there are two type - (1)= single line comment = #
# (2)= multi line comment = '''_____''' / """___"""
# generaly use '''___''' code

# string formating ( achhe se dikhana)
year = 2024
company = "regex softwere"
print ("year is ",year ,"company is ", company)

year = 2024
company = "regex softwere"
print (f"year is {year} company is  {company}")
# string formetting is just a way to repersent the data

username = " shiv "
print(f"hello {username}")

username = " shiv "
msg= f"hello {username}"

print(msg)

username = " shiv "
msg= f"hello {username}"

print(msg)

username=" sonu "
print(msg)
# hamne username change kiya h pr massge ki value to vhi h .

username = " shiv "
msg= f"hello {username}"

print(msg)

username=" sonu "
msg=f"hello{username}"
print(msg)

