# -*- coding: utf-8 -*-
"""day10dictionary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gH1zr78Y5QjaxCRyN0Krr1IuFjVXApf8
"""

# dictionary => a collection of key and value pair .
# key => a uniqe identifire (jiski help se ham chijo ko exix krege ).
# value => yh ek data h jo associated a key .
# key + value => dictionary
# muteble
# orderd
# unindex position
# agar koi data exix krna h to key se hi exix kroge .

mydictionary = {1:"abc", 2:"def","age":100}

mydictionary

# change element =>
mydictionary[1] = "xyz"

mydictionary

# append =>
mydictionary["gender"] = "male"

mydictionary

# insert element =>
mydictionary.update({3:"pqr"})

mydictionary

# delete =>
del mydictionary[2]

mydictionary

# exix krna =>
mydictionary[1]

# check elememt =>
"age" in mydictionary

"name" in mydictionary

mydictionary['age']

# add list in dictionary =>
# dictionary[key].append(value)
mydictionary['name'] = ["shiv","kishan"]

mydictionary

# list exix krna =>
mydictionary['name']

# update value =>
mydictionary['name']="shiv"

mydictionary

# insert value =>
mydictionary['rollno.']=10
# agar value disctionary me nhi h to vo insert ho jayegi .

mydictionary

mydictionary={1: 'xyz', 'age': 100, 'gender': 'male', 3: 'pqr', 'name': ['shiv', 'kishan'],1:"aman"}
print(mydictionary)

# jo letest vali key h use phle add kr dega .

#  dlete by pop method =>
mydictionary.pop(1)

mydictionary

del mydictionary["age"]

mydictionary

# element ko variable me store krna =>
a = mydictionary.pop(3)

a

mydictionary

# disctionary me keys dekhna =>
mydictionary.keys()

# disctionary me value dekhna =>
mydictionary.values()

# dictionary me key or value dono dekhna =>
mydictionary.items()

mydictionary.popitem()

mydictionary={1: 'xyz', 'age': 100, 'gender': 'male', 3: 'pqr', 'name': ['shiv', 'kishan'],1:"aman"}

# run a loop on dictionary =>
for i in mydictionary:
    print(i)

# output me keys print hogi .

for i in mydictionary.keys():
    print(i)

for i in mydictionary.values():
    print(i)

# sabhi key ki value print krna =>

for i in mydictionary:
    print(i , mydictionary[i])

# agar tuple format me kisi data ko dke to agar tuple me do element (10,20) h to phle vale ko key [10] or dusre vali value [20] , but agar y (10,20,30) ho gye to y value format me aa jayegi .
dict=([(10 , 20)])
print(dict)

# craete a list =>
[10,20]

# add in tuple =>
[(10,20)]

# ab is list me ek hi element h or vo h tuple .

[ (10,20) , (30,"abc") ]

# ab list me 2 tuple  ho gye ya 2 element aa gye .
# 1st tuple (10,20) and 2nd is (30,"abc") .

dict = ( [ ( 10 , 20 ) , ( 30 , "anc" ) ] )

dict

x=[(10, 20), (30, 'anc')]
x.items()

# run a loop on list
for i in [(10, 20), (30, 'anc')]:
    print(i)

# loop chlne pr tuple format me o/p aayega.

# tuple me index nikalna =>
for i in [(10, 20), (30, 'anc')]:
    print(i , i[0], i[1])

# tuple se nikle index ko alag alag variable me print krna =>
for i in [(10, 20), (30, 'anc')]:
    x=i[0]
    y=i[1]
    print(i)

x

y

i=(10, 20)
x , y = i
print(x)
print(y)

i=(10, 20 ,100)
x , y = i
print(x)
print(y)

i=(10, 20 , 100)
x , y ,z = i
print(x)
print(y)
print(z)

# jitne number of value h utne hi variable bna lo .

# tuple se value ko nikalna =>
for tuple in [(10, 20), (30, 'anc')]:
    x,y=tuple
    print(x , y )

x={10:20 , 30:"abc"}
x.items()

# dirctly loop dictonery pr bhi chala skte h .
x={10:20 , 30:"abc"}
for i in x.items():
    print(i)

x={10:20 , 30:"abc"}
for i in x.items():
    key , value = i
    print(key , value)

for key , value in x.items():
    print(key , value)

