# -*- coding: utf-8 -*-
"""day2operators.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eV_-4ci-BP7q5Wk-tTKE4HVwkKAHrjLk
"""

# operator
# symbol => jo task perform krta h
# expression ( jab solve hooga tab boutput aayega )
# ex.
1+2
# jhan 1,2 oprets( jiske uper yh opretion hua ) h or + operator h jo dono value ko add krega .

# types of operator's
# (1). Arithmetic operator
# + =>
1+2

# - =>
5-4

# * =>
5*4

# / =>
5/2

# // =>
5//2
# floor division (only int. value )

# ** (power)=>
2**2

# % (moduler / remender)=>
10%2

11%2

10.0+5
# jo bada datatype hota h hamesha usme value add  hoti h.

1+6/5*6-5+5
# hamne / use kiya h value float me aayegi .
# agar // use krte to value int. me aati

1+6//5*6-5+5

# priority order of a arithmetic operator =>
# **
# * , / , // , %
# + , -
# y hamesha left to right chalta h .

# (2). Comparision operator =>
# - comapre value
# - answer only " true " , " false " .

10>5

52<50

10==10

# (3). Assignment operator .=>
# assin krne ke liye .
# python me binary operator ( jisme 2 value honi hi chahiye ) work krta h .
# x=10
# x+y => binary operator

x=10
x+15
print(x)
# 2nd line me x ki value ko assine nhi kiya gya .

x=10
x=x+15
print(x)

x=10
x+=15
print(x)

age = 18
age //=5
print(age)

# (4). Logical operator's =>
# 1 se jyada condition ko check karne ke liye .
# there are three type =>

# (a). and operator => dono condition shi hogi to ture nhi to false .

x=10
x>4 and x<5

x=10
x>4 and x<15

# (b). or operator => dono me se koi 1 hi shi hp jaye .
x=10
x>4 or x<5

# (c). not operator => right ko wrong krne ke liye .
not(True)

# True or false likhte time first latter hamesh capital hona chahiye .

not ( False )

not (x==10)

# Membership operator =>
# kya koi value belong krti h kisi orr value me to membershio operator use kiya jata h .
# ye kisi kisi datatype ke sath hi chalta h .
# ye int.type value pr nhi chalta h .

# (1) in (h)=>

"R" in " RAJASTHAN"

# (2) not in ( nhi h ) =>

"z" not in "rajasthan"

"RA" in " RAJASTHAN"

"RJ" in " RAJASTHAN"

# Identify operator =>
# aise operator jo uski identification check kre .
# agar variable kisi class , datatype se belong kr rhe h to iske liye identy operator kam liya jata h .

x=10
print(type (x))

type (x) is int

# is check krega " kya y data kisi class ko belong kr rha h ya kisi ka part h ya nhi h"

type (x) is str

type (x) is not str

# string nhi h y check kiya h not lga kr

x=500
y=500

x==y

x is y

# kyunki dono ki value same h but is operator puri memory address ko check krta h " x or y dono ke pas alag alg memory address h "

x1 = 560
y1 = x1 # x1 ki value hi y1 ko mil jani chahiye .

print(y1)

x1 = 560
y1 = x1

x1==y1

x1 is y1

# Bitwise / bits operator =>
# hamesha chije 2ki power me print hogi
# 8421 ke combination se 15 tk koi bhi nomber bna skte h .
# agar uper or niche dono value 1,1 hui to "1" nhi to "0"
# symbol = &
# yah un system pr chalta he jhan pr " RAM " " MEMORY " ki kami hoti h

11 & 13

6 & 13

# "|" iski condition yh h ki agar dono bit 1 h to "1" nhi to "0" lo .

6 | 14

# Bitwise shifts operator =>
# (1). bitwise right shift =>

10>>1

15>>2

