# -*- coding: utf-8 -*-
"""day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RksakmJffXBaRrs53zrD3p1zUYPoOiel
"""

# >10= nomber then 10 .
# s => nomber is also divisbile by 5 .

num=10
if(num>10):
    print("nomber is grater than 10")

else:
    print("nomber is not grater than  or equal to 10")

num=int(input("enter the nomber : "))
if(num>10):
    print("nomber is grater than 10")

else:
    print("nomber is not grater than  or equal to 10")

num=int(input("enter the nomber : "))
if(num>10):
    print("nomber is grater than 10")

else:
    print("nomber is not grater than  or equal to 10")

# 2nd condition add krna :-

num=int(input("enter the nomber : "))
if(num>10):
    print("nomber is grater than 10")
    if(num%5==0):
      print("nomber divided by 5")
    else:
      print("nomber is not diviseble by 5")

else:
    print("nomber is not grater than  or equal to 10")

# Looping statement .=>
# - repetatively
#

print("shiv")
print("shiv")
print("shiv")

# Loops = jisme koi bhi task multiple time krte h .

# (1). For loop _=>

# syntex= for i in range (0,10)
# range function ka kaam value ko generate krna hota h .
# range ke andar 3 type add hote h . (starting value , ending value [step size = 1(default)])

for i in range (0,10):
    print(i)

for i in range (1,5):
    print(i)

for i in range (1,10,2):
    print(i)

for i in range (0,10,2):
    print(i)

for i in range (0,6,1):
    print(i)

for i in range (0,6,-1):
    print(i)

# kyunki jana 1 se 6 h to step size + honi chahiye but yha - h to ye loop nhi chalega .

for i in range (6,0,-1):
    print(i)

for i in range (4,16,3):
    print(i)

for i in range (10,6):
    print(i)

# by deault step size +1 hoti  but yhan pr loop ulta chalna h to step size ko - me likhna hoga tabhi y loop chalega .

for i in range (10,6,-1):
    print(i)

# to print all the even nomber 1-7 ?

for i in range (1,8):
    if(i%2==0):
        print("even")

    else:
        print("odd")

    print(i)

for i in range (1,8):
    if(i%2==0):
        print(i)

# total =>

sum=0
for i in range (1,8):
    sum +=i


print(sum)

# run a loop from 100 to 2 and we need to calculate the total of all the nomber devisible by 7 ?

total=0

for i in range (100,2,-1):
    total +=i

    if(total%7==0):
      print(i)

print(total)

total=0

for i in range (100,2,-1):
    total +=i

print(total)

total=0

for i in range (100,1,-1):
    if (i%7==0):
      total +=i

print(total)

for i in range (100,1,-1):
    if (i%7==0):

      print(i)

# total nmber jo 7 se diveded h .

total=0

for i in range (100,1,-1):
    if (i%7==0):
      total +=i

print(total)

# string loop =>

for i in "hello":
     print(i)

data  = " hello shivpal "

for char in data:
    print(char)

data  = " hello shivpal "

for char in data:
    print(char , end="\n")

# \n by default value h .

# agar ham chahte h ki ek hi lin eme print ho to \n ko remove kr skte ho .

data  = " hello shivpal "

for char in data:
    print(char , end=" ")


# agar charector me space bhi nhii dena chahte to bich me white space ko bhi remove kr do .

data  = " hello shivpal "

for char in data:
    print(char , end="")

# charector count krna -=>

data = " hello shivpal"

count=0

for char in data:
    count +=1

print(count)

#  user se input leker charector count krna =>

data = str(input("enter the value in string formate : "))

count=0

for char in data:
    count +=1

print(count)

# String data using index =>

# len function = total nomber of char.

len("hello")

data="jaipur"

for i in range(0,6):
    print(i,data , data[0])

data="jaipur"

for i in range(0,6):
    print(i,data , data[i])

#  kyunki i ki value menualy 0 - 6 ja rhi h baar baar value dene ki jrurt na h .

data="jaipur"

for i in range(0,6):
    print(i, data[i])

data="jaipur"

for i in range(0,6):
    print(data[i])

data="jaipur"

for i in range(0,len(data)):
    print(data[i])

data="jaipur udaipur jodhpur"

for i in range(0,len(data)):
    print(data[i])

x="hello shivpal singh dewra "

for char in x:
    if char in "a,e,i,o,u":
        print(char)

data="jaipur"
for char in data:
    if char in "a,e,i,o,u":
        print(char)

for x in " jaipur":
    if(x in "aeiou"):
          print("vowel is : ", x)

for x in str(input("enter the str. char. : ")):
    if(x in "aeiou"):
          print("vowel is : ", x)

for x in str(input("enter the str. char. : ")):
    if(x=="a" or x=="e" or x=="i" or x=="o" or x=="u"):
          print("vowel is : ", x)

