# -*- coding: utf-8 -*-
"""day5whileloop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n6m-wmnh7aSn2pghQhcG4O2oA5Nz2lGq
"""

# count how many nomber are there from 2 to 500
# 7 and 11

total=0
for num in range (2 , 501):
    if num % 7 == 0 and num % 11 == 0:
        total+=1
        print(num)
print(total)

total=0
for num in range (int(input("enter starting value")), int(input("enter ending value"))):
    if num % 7 == 0 and num % 11 == 0:
        total+=1
        print(num)
print(total)

total=0
for num in range (int(input("enter starting value")), int(input("enter ending value"))):
    if num % 3 == 0 and num % 7 == 0:
        total+=1
        print(num)
print("total nomber  is :" ,total)

# total function kaise work krta h ?
# = jab jab value milegi to usme hamesha 1 add ho jayega or loop aage chlega .

# Factors nikalna =>
# 10 => 2,5,10 .

# loop string .

for i in " shiv ":
    print(i)

# string loop and hoe many consonent are there .
for i in " shivpal singh dewra ":
    if i not in "aeiou":
        print(i , end=" ")

# While loop =>

'''
iska use tab kiya jata h tab aapko pata nhi hota ki aapko apna loop kitni baar chalana h .

ex. FOR LOOP =
 i need to find out all the nombers which are devisible by 7 and 11 from 1 to 100 .

    WHILE LOOP =
i need to find out the starting 50 nomber which are devisible by 7 and 11 .

- jab aapko pata nhi hota h ki aapko apna loop khan se khan tak chalana h .

'''

# same working ->

for i in range (1,10):
    print(i)

'''i=1
while (i<5):
    print(i)'''

# y loop infi. chalega kyunki isme condition ko false kiya hi nhi

i=1
while (i<5):
    print(i)
    i+=1

# starting 15 nomber => 2 and 6 and 7 diviseble

count=0 # create a variable
num=7
while(count<15):
    if (num%2==0 and num%6==0 and num%7==0):
        count+=1
        print(num , "count :" ,  count)
    num+=1

print("y vo nomber h jo 2 , 6 or 7 se dived h ")

# starting 15 nomber => 2 and 6 and 7 diviseble

count=0 # create a variable
num=7
while(count<25):
    if (num%2==0 and num%6==0 and num%7==0):
        count+=1
        print(num , "count :" ,  count)
    num+=1

print("y vo nomber h jo 2 , 6 or 7 se dived h ")

# 137 se 5 tk while loop .

num=137
while num>5:
    num=num-1
    print(num)

num=50
while num>5:
    num-=1
    print(num)

# y loop tab tak chalega jab tak value 5 nhi aaye .

# ARMSTRONG NOMBER =>

# 153
# 1                5            3
# 1**3             5**3         3**3
# 1                125          27
# total => 153

x = 153
rem1 = x%10

x//10

x = 153
rem1 = x%10

x=x//10

x%10

rem2 = x%10

x=x//10

x

rem3 = x%10
x=x//10

rem1

rem2

rem3

rem1**3 + rem2**3 + rem3**3

x = 371
rem1 = x%10

x//10

x=x//10

x%10

rem2 = x%10

x=x//10

rem3 = x%10
x=x//10

rem1**3 + rem2**3 + rem3**3

x = 343
rem1 = x%10

x//10

x=x//10

x%10

rem2 = x%10

x=x//10

rem3 = x%10
x=x//10

rem1**3 + rem2**3 + rem3**3

