# -*- coding: utf-8 -*-
"""day6pattern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i_kDOWx4SMf75OIeXaST7x7YGVeN3pkt
"""

# Pattern =>
for i in range (1,5):
    print("shiv")

for i in range (1,5):
    for j in range(1,4):
        print(i , j)

# harek i ke liye j ki value 3 baar chal rhi h.

for i in range (1,5):
    for j in range(1,5):
        print(i , j)

for i in range (1,5):
    for j in range(1,5):
        print("*")

for i in range (1,5):
    for j in range(1,5):
        print("*", end=" ")

for i in range (1,5):
    for j in range(1,5):
        print("*", end=" ")

    print(" ")

for i in range (1,5):
    for j in range(1,5):
        print("*", end=" ")

        print(" ")

for i in range (1,4):
    for j in range(1,5):
        print(i, end=" ")


    print(" ")

for i in range (1,4):
    for j in range(1,5):
        print(j, end=" ")


    print(" ")

for i in range (10,15):
    for j in range(10,15):
        print(j, end=" ")


    print(" ")

for i in range (5,1,-1):
    for j in range(5,0,-1):
        print(j, end=" ")


    print(" ")

for i in range (5,1,-1):
    for j in range(5,0,-1):
        print(i, end=" ")


    print(" ")

for i in range (5,0,-2):
    for j in range(5,0,-1):
        print(i, end=" ")


    print(" ")

for i in range (1,5):
    for j in range(1,i+1):
        print("*", end=" ")


    print(" ")

for i in range(1,5):
    for j in range(1,i+1):
        print(i,j, end=" ")

    print(" ")

n=6
for i in range (1,6,1):
    for j in range (1,6,1):
            print(n-j , end=" ")
    print("")

for i in range (1,5):
    for j in range (0,5-i):
        print("*",end="  ")

    print(" ")

for i in range (1,5):
    for j in range (1,6-i):
        print("*",end=" ")

    print("")

