# -*- coding: utf-8 -*-
"""day7patterns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VbPGWqYAZB88vvE8cPCocldDL2-m6SPG
"""

for  i in range (1,4):
      for j in range (1 , 4-1):
          print(" " , end=" ")

      for k in range (1 , i+1):
          print("*", end=" ")

      print(" ")

for  i in range (0,5):
      for j in range (1 , 5-i):
          print(" " , end=" ")

      for k in range (1,2*i):
          print("*", end=" ")

      print(" ")

for  i in range (6,1,-1):
      for j in range (i,6):
          print(" " , end="")

      for k in range (1,i):
          print("*", end=" ")

      print(" ")

for i in range (4,0,-1):
    for j in range(0,4-i):
        print(" ",end="")

    for k in range (0,2*i-1):
        print("*",end="")

    print("")

