# -*- coding: utf-8 -*-
"""day9list&touple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Em2rPR4bPzFHRezKOYxErzqAQzoUe3ry
"""

# List data type =>
# list = data structure
# collect multiple element
# sequence data type
# index position
# mutable
# orderd

mylist=[]
print(type(mylist))

mylist=[1,2,3,4,5,"hello"]
print(mylist)

# exix => index position se

mylist=[1,2,3,4,5,"hello"]
print(mylist[0])

mylist=[1,2,3,4,5,"hello"]
print(mylist[-1])

mylist=[1,2,3,4,5,"hello"]
print(mylist[1:4])

# update value =>
mylist=[1,2,3,4,5,"hello"]
mylist[0]=100
print(mylist)

mylist=[1,2,3,4,5,"hello"]
mylist.extend("abc")
print(mylist)

mylist=[1,2,3,4,5,"hello"]
mylist.extend([10,20,30])
print(mylist)

# insert value =>
mylist=[1,2,3,4,5,"hello"]
mylist.insert(0,100)
print(mylist)

# add element =>
mylist=[1,2,3,4,5,"hello"]
mylist.append(100)
print(mylist)

# change element =>.
mylist=[1,2,3,4,5,"hello"]
mylist[0]=100
print(mylist)

# delete value =>
mylist=[1,2,3,4,5,"hello"]
mylist.pop()
print(mylist)

# value ko variable me store karan .
mylist=[1,2,3,4,5,"hello"]
x=mylist.pop()
print(mylist)

print(x)

# index vise data delete krna .
mylist=[1,2,3,4,5,"hello"]
mylist.pop(0)
print(mylist)

print(help(mylist))

# clear =>
# sara data clear ho jata h
mylist=[1,2,3,4,5,"hello"]
mylist.clear()
print(mylist)

# reverse =>
# isse reverse print hota h .
mylist=[1,2,3,4,5,"hello"]
mylist.reverse()
print(mylist)

# count =>
mylist=[1,2,3,4,5,"hello"]
mylist.count(1)
print(mylist)

mylist=[1,2,3,4,5,"hello"]
mylist.count(10)
print(mylist)

# copy =>
# list ka data copy krne ke liye .
mylist=[1,2,3,4,5,"hello"]
mylist2=mylist.copy()
print(mylist2)
print(mylist)

# specific position pr kuchh insert krna =>
mylist=[1,2,3,4,5,"hello"]
mylist.insert(0,100)
print(mylist)

# dirct element delete krna ya remove krna .
mylist=[10,2,3,4,5,"hello",10]
mylist.remove(10)
print(mylist)
# jo element sabse phle h vo delete hoga y ye value ki hisaab se delete hoga .

# empty list se reprass krna =>
mylist=[1,2,3,4,5,"hello"]
mylist[1:3]=[]
print(mylist)

# list => itrable
# for loop
# while loop
mylist=[1,2,3,4,5,"hello"]
for i in mylist:
    print(i)

# index
mylist=[1,2,3,4,5,"hello"]
len(mylist)

# index using while loop
mylist=[1,2,3,4,5,"hello"]
count=0
while count<len(mylist):
    print(mylist[count])
    count+=1

# index using for loop =>
mylist=[1,2,3,4,5,"hello"]
for i in range(len(mylist)):
    print(mylist[i])

for i in mylist:
    print(i)

# condition me only int. print karana .=>
mylist=[1,2,3,4,5,"hello",20.32,56,520]
for i in mylist:
    if type(i)is int:
        print(i)

# sabhi element ka squere nikalna .=>
mylist=[1,2,3,4,5,"hello",20.32,56,520]
for i in mylist:
    if type(i)is int:
        print(i**2)

# sabhi element ko newlist me add krna .=>
mylist=[1,2,3,4,5,"hello",20.32,56,520]
newlist=[]
for i in mylist:
    if type(i)is int:
        newlist.append(i**2)

print(newlist)

mylist=[1,2,3,4,5,"hello",20.32,56,520]
newlist=[]
for i in mylist:
    if type(i)is int:
        newlist.append(i**2)

    print(newlist)

mylist=[1,2,3,4,5,"hello",20.32,56,520]
newlist=[]
for i in mylist:
    if type(i)is int:
        newlist.append(i**2)

        print(newlist)

mylist=[1.0,20,10,60.0,5,30]
newlist=[]
for i in mylist:
    if type(i)is int:
        newlist.append(i**2)

        print(newlist)

mylist =["hello" , "hey" , "tushar" , "regex"]
newlist=[]
total=0
for i in mylist:
    if type(i)is str :
        newlist.append(len(i))
        total+=len(i)

print(newlist)

mylist =["hello" , "hey" , "tushar" , "regex"]
newlist=[]
total=0
for i in mylist:
    if type(i)is str :
        newlist.append(len(i))
        total+=len(i)

    print(newlist)

mylist =["hello" , "hey" , "tushar" , "regex"]
newlist=[]
total=0
for i in mylist:
        newlist.append(len(i))
print(newlist)

"""**TUPLE**"""

# touple
# immutble
# multiple data type element store
# index position
# orderd
# faster

mytuple=(1,2,3,4,5,"hello")
print(mytuple)

mytuple=10
print(type(mytuple))

mytuple=10 , 20
print(type(mytuple))

mytuple=(10,20,30)
print(type(mytuple))

mytuple=10,20,"shiv"

mytuple

# index data ko exix krna .
mytuple=(10,20,30)
print(mytuple[0])

# count =>
# ki value kitni baar aayi h .
mytuple=(10,20,30)
mytuple.count(10)

print(help(mytuple))

mytuple=(10,20,30)
mytuple+(40,50,60)

# variable me store krna .
mytuple=(10,20,30)
mytuple=mytuple+(40,50,60)
print(mytuple)

# tuples are immutable but reference  ya memory address alg alg  h .

mytuple=(10,20,30)
print(id(mytuple))
mytuple=mytuple+(40,50,60)
print(id(mytuple))
print(mytuple)

# tiples me changes hoge to vo new memory address change krega .

