# -*- coding: utf-8 -*-
"""GCD finder (gretest common divisor).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GuKuwVVD9bzIvmGte5EpgcGP8H86tAiS
"""

# GCD (gretest common divisor ) finder =>
def gcd(a,b):
    # calculate the greatest common divisor of two two nomber using the eulidean algorithm .
    while b != 0:
        temp = b
        b = a % b
        a = temp
    return a

num1 = int(input("enter the first nomber :"))
num2 = int(input("enter the second nomber :"))
gcd_value = gcd(num1 , num2)
print("the GCD of", num1 , "and" , num2 , "is" ,gcd_value)

