# -*- coding: utf-8 -*-
"""reverse&palindrom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ycYndVQTlIm_Djv2nsPNMZtPGKiifzob
"""

# reverse nomber =>

# take input

number =int(input("enter the number = "))
temp = number
reverse = 0

while(number>0):
    digit = number%10
    reverse = (reverse*10)+digit
    number = number//10

print(reverse)

#  palindrom nomber =>

# take input

number =int(input("enter the number = "))
temp = number
reverse = 0

while(number>0):
    digit = number%10
    reverse = (reverse*10)+digit
    number = number//10

if temp == reverse:
    print("nomber is palindrom")

else:
    print("nomber is not palindrom")

