# -*- coding: utf-8 -*-
"""table using for loop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kBuQ13zrFBelIvAJkCOP1yCLmPjpZ_zP
"""

# pyhton multiplication table using the for loop .
num = int(input("Enter a number: "))
for i in range(1, 11):
    print(num, 'x', i, '=', num*i)

